spring:
  datasource:
    dbcp2:
      url: jdbc:mysql://localhost:3306/springboot-demo?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 2
      max-total: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
    type: org.apache.commons.dbcp2.BasicDataSource

logging:
  level:
    root: info
    org:
      mybatis: debug
    com:
      philcode:
        springboot:
          mybatis:
            mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql